# Generated by Django 6.0.6 on 2026-06-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalshi_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='realized_pl_cents',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
