# Generated by Django 6.0.6 on 2026-07-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalshi_api', '0003_forecastsnapshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForecastSnapshot',
        ),
    ]
